version: "2"
services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./html_data:/var/www/html

  mysql:
    image: centos/mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_log:/var/log/mariadb